Repository AdobeDocs/commerce-contributor, pull requests merged in 2022-04, with the labels that each got.

#2 Initial repo setup
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pull-request.yml
  .markdownlint.json
  gatsby-config.js
  package-lock.json
  package.json
  src/data/navigation/header.js
  src/data/navigation/index.js
  src/data/navigation/sections/guides.js
  src/data/navigation/sections/index.js
  src/pages/api/1.4.md
  src/pages/api/index.md
  src/pages/community/experience_cloud.png
  src/pages/community/index.md
  src/pages/community/stack-overflow.png
  src/pages/guides/calculated_metrics_api/index.md
  src/pages/guides/code-contributions/backward-incompatible-development.md
  src/pages/guides/code-contributions/definition-of-done.md
  src/pages/guides/code-contributions/index.md
  src/pages/guides/creating_oauth_client/index.md
  src/pages/guides/discovery_api/index.md
  src/pages/guides/index.md
  src/pages/guides/jwt_authentication/index.md
  src/pages/guides/migrating/index.md
  src/pages/guides/oauth_using_curl/index.md
  src/pages/guides/oauth_using_postman/index.md
  src/pages/guides/reporting_api/index.md
  src/pages/guides/reporting_api/reporting_breakdowns/index.md
  src/pages/guides/reporting_api/reporting_breakdowns/reporting_multiple_breakdowns/index.md
  src/pages/guides/reporting_api/reporting_tips_tricks/index.md
  src/pages/guides/segments_api/index.md
  src/pages/index.md
  src/pages/support/FAQ/index.md
  src/pages/support/community/index.md
  src/pages/support/contribute/index.md
Labels: enhancement

#4 COMDOX-212: Migrate contributor guide from magento/devdocs
  .DS_Store
  .gitignore
  package.json
  src/data/navigation/header.js
  src/data/navigation/sections/guides.js
  src/pages/_images/approve-changes.png
  src/pages/_images/bitegria.png
  src/pages/_images/builds-and-checks.png
  src/pages/_images/code.svg
  src/pages/_images/contributors.svg
  src/pages/_images/deployment-comments.png
  src/pages/_images/doc.svg
  src/pages/_images/edit-report.png
  src/pages/_images/experience-cloud.svg
  src/pages/_images/green-check.png
  src/pages/_images/maintainers.svg
  src/pages/_images/pr-code-review.png
  src/pages/_images/pr-dashboard.png
  src/pages/_images/pr-target-branch.png
  src/pages/_images/red-x.png
  src/pages/_images/related-prs.png
  src/pages/_images/repo-and-projects.png
  src/pages/_images/slack-channel.png
  src/pages/_images/slack.svg
  src/pages/_images/stack-exchange.svg
  src/pages/_images/stack-overflow.png
  src/pages/_images/test-coverage-labels.png
  src/pages/community/experience_cloud.png
  src/pages/community/index.md
  src/pages/guides/code-contributions/backward-compatibility-policy.md
  src/pages/guides/code-contributions/backward-incompatible-development.md
  src/pages/guides/code-contributions/definition-of-done.md
  src/pages/guides/code-contributions/index.md
  src/pages/guides/code-contributions/phpstorm-code-inspections.md
  src/pages/guides/code-contributions/processing-workflow.md
  src/pages/guides/code-contributions/pull-request-tests.md
  src/pages/guides/contributors/index.md
  src/pages/guides/doc-contributions/index.md
  src/pages/guides/index.md
  src/pages/guides/maintainers/handbook.md
  src/pages/guides/maintainers/index.md
  src/pages/index.md
Labels: migration

#5 Removed unnecessary file
  .DS_Store
Labels: maintenance

#6 Update .gitignore
  .gitignore
Labels: maintenance

#7 COMDOX-213: Migrate community resources from magento/devdocs
  src/data/navigation/sections/community.js
  src/data/navigation/sections/index.js
  src/pages/community/best-practices.md
  src/pages/community/contribution-programs.md
  src/pages/community/index.md
  src/pages/community/organizer-handbook.md
  src/pages/community/support.md
  src/pages/index.md
Labels: migration

#8 COMDOX-226: Migrate contributor install topics from magento/devdocs
  src/data/navigation/sections/guides.js
  src/pages/_images/install.svg
  src/pages/guides/index.md
  src/pages/guides/install/change-version.md
  src/pages/guides/install/clone-repository.md
  src/pages/guides/install/index.md
  src/pages/guides/install/update-dependencies.md
Labels: migration
