Repository AdobeDocs/commerce-contributor, pull requests merged in 2023-11, with the labels that each got.

#101 Update workflows with deployments
  .github/workflows/publish.yml
  .github/workflows/stage.yml
Labels: maintenance

#102 Sync deployment workflows
  .github/workflows/publish.yml
  .github/workflows/stage.yml
Labels: maintenance

#103 Typo fix
  src/pages/guides/code-contributions/index.md
Labels: editorial

#104 Add a linter to validate external links
  .remarkrc.mjs
  package.json
  src/pages/community/support.md
  src/pages/guides/install/update-dependencies.md
  src/pages/guides/maintainers/index.md
  yarn.lock
Labels: enhancement

#105 Add validation for custom headers
  .remarkrc.mjs
  package.json
  yarn.lock
Labels: bug, enhancement

#106 Update theme and caniuse-lite
  package.json
  yarn.lock
Labels: dependencies, maintenance
